CREATE PROCEDURE ListarALUMNO
AS
BEGIN
 SELECT * FROM ALUMNO
 end
 go

EXEC ListarALUMNO



CREATE PROCEDURE DELETEALUMNO
@CODIGO INT
AS BEGIN 
DELETE FROM ALUMNO 
WHERE CODIGO = @CODIGO
END
GO
EXEC DELETEALUMNO @CODIGO='2'



CREATE PROCEDURE UPDATEALUMNO
@CODIGO INT,
@DIRECCION varchar(50),
@TURNO VARCHAR(50),
@ESTADO VARCHAR(50)
AS BEGIN
  UPDATE ALUMNO SET (CODIGO, DIRECCION, TURNO, ESTADO) WHERE  CODIGO=@CODIGO
  GO
EXEC UPDATEALUMNO @CODIGO=''

-----------STORE PROCEDURES  APODERADOS---------------

CREATE  PROCEDURE INSERTAPODERADO	
@NOMBRE VARCHAR (50),
@ESTADO VARCHAR(50)
AS 
BEGIN 
INSERT INTO APODERADO (NOMBRE, ESTADO) VALUES  (@NOMBRE, @ESTADO)
END 


EXEC INSERTAPODERADO @NOMBRE='ZECARLOS', @ESTADO='DISPONIBLE'



CREATE PROCEDURE LISTARAPODERADO
AS
BEGIN 
SELECT * FROM APODERADO
END
GO

EXEC LISTARAPODERADO

CREATE PROCEDURE DELETEAPODERADO
@CODIGO INT
AS BEGIN 
DELETE FROM APODERADO
WHERE CODIGO = @CODIGO
END
GO

EXEC DELETEAPODERADO @CODIGO='1'


CREATE PROCEDURE UPDATEAPODERADO
@CODIGO INT,
@NOMBRE VARCHAR(50),
@ESTADO VARCHAR(50)
AS
BEGIN 
UPDATE APODERADO SET CODIGO,NOMBRE,ESTADO WHERE CODIGO=@CODIGO
END
GO

EXEC UPDATEAPODERADO @CODIGO=''